### ISSUE TITLE
Unalphabetized name condition can break libcolonyfind

### ISSUE THREAD

**Issue by john-fike** [msudesigncpr/slate-ui#14] opened 2024-04-24 20:08 UTC
libcolonyfind parses petri dish image files alphabetically, so if the user specifies names that are not in alphabetical order, libcolonyfind will break. Namely, x coord OOB check will not reliably work, and annotation will be completely incorrect. 

This has been fixed by will, but the fix will not be turned on until testing is complete.

**Comment by w-culhane** [comment] 2024-04-24 20:21
Duplicate of #7

**Closed as not planned by w-culhane** 2024-04-24 20:21 UTC
Labels: bug, priority:LOW
